### ISSUE TITLE
Feature Request: Read sensitive keys from the environment / .env file

### ISSUE THREAD

**Issue by andreynering** [gobackup/gobackup#117]
Pasting passwords or secrets directly on the YAML seems non-ideal, because that file will possibly be commited on the Git repository, for example.

More ideal would be to read from a `GOBACKUP_ENC_PASSWORD`/`GOBACKUP_S3_ACCESS_KEY` environment variables, which could be set on the OS level or on a `.env` file. A separate `.env` file could be ignored in `.gitignore`, avoiding exposing the password.

**Comment by huacnlee** [comment]
Hi @andreynering 

We just released v1.6.0 with ENV variable support.

**Comment by andreynering** [comment]
Awesome, thanks!
