### ISSUE TITLE
请求 Releases 发布 Linux ARM64

### ISSUE THREAD

**Issue by Anbool** [gobackup/gobackup#122]
老哥最近属实高产，非常感谢！已经用了很多年了，1.0.0 版本的时候还提供了 Linux AMR64，之后的版本又没了，最近更新频繁，我手里有一些 ARM64 的机器，每次都要手动编译，挺麻烦的，老哥要是每次发布的时候能编译好 ARM64 最好，要是不方便我就自己编译也行。

**Comment by huacnlee** [comment]
你试试 https://github.com/gobackup/gobackup/releases/tag/v1.6.3

**Comment by Anbool** [comment]
> 你试试 https://github.com/gobackup/gobackup/releases/tag/v1.6.3

感谢老哥！
