### ISSUE TITLE
Context timeout for MongoDB prevent big backups

### ISSUE THREAD

**Issue by snird** [gobackup/gobackup#124]
A ~500GB collection takes ~5 hours to get the dump out.
The output file is typically 3x the size, so in this example case 1.5TB.

We get `context deadline exceeded` error, regardless of what we do.

I can't tell from the error where it happens - waiting for the dump to be done or waiting for the file upload to storage to be done.
Either way, it seems like the code can't handle big files as it is (no such issues with a bash script doing the same)

**Comment by huacnlee** [comment]
Would please upload your ~/.gobackup/gobackup.log

**Comment by snird** [comment]
Resolved with assigning much bigger timeout value for azure
