### ISSUE TITLE
sqlite3: invalid backup command

### ISSUE THREAD

**Issue by rprtr258** [gobackup/gobackup#150]
while performing sqlite3 model backup gobackup gave following error:
```
2023/05/01 08:12:00 [SQLite] -> Dumping SQLite...
2023/05/01 08:12:09 [Database] Dump failed
2023/05/01 08:12:09 [Model] Cleanup temp: /tmp/gobackup1634970779/
2023/05/01 08:12:09 [Model: twitch_bot_db] Error: in prepare, near ">": syntax error
  >
  ^--- error here
```

I understood nothing from error message, so looked into the source code. There I found that sqlite3 backup builds following command here https://github.com/gobackup/gobackup/blob/main/database/sqlite.go#L35
```go
	args := []string{
		"sqlite3",
		db.path,
		".dump",
		">",
		db._dumpFilePath,
	}
	return strings.Join(args, " ")
```
which is then passed to `os/exec.Command`. That won't work because `>` is interpreted as command argument, so instead of running `sqlite3 "db.db" ".dump" > "dump.file"` it will run `sqlite3 "db.db" ".dump" ">" "dump.file"` and cause error above.

To circumvent the issue you should either not use any sh/bash specific staff in arguments, just command and it's arguments, or use `sh -c 'command goes here'` to run command using shell.

**Comment by huacnlee** [comment]
Fix in v2.0.2

**Comment by rprtr258** [comment]
in commit https://github.com/gobackup/gobackup/commit/91d270a5df3709a1722bac8ebf926a01c2b952aa
you changed wrong command
`sqlite3 "db.db" ".dump" ">" "dump.file"`
to another still wrong command
`sqlite3 "db.db" ".dump > dump.file"`

and added test tests nothing because it runs
`sqlite3 "" ".dump > dump.file"`

which for some reason don't print error and don't fail with non-zero exit code and prints
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
COMMIT;
```
to stdout thus passing the test

That happend because in `sqlite3.yml` `path: tests/fixtures/test.sqlite3` must be used instead of `database: tests/fixtures/test.sqlite3`.

Even after fixing that, command
`sqlite3 "tests/fixtures/test.sqlite3" ".dump > /tmp/gobackup1696003324/1683297657560108024/test/sqlite/sqlite3/test.sql"`
is executed which still instead of failing prints same text.

Even if sqlite3 wrongly parses argument with `.dump ...` file `...test.sql` is not saved and won't be because `>` is still part of `sqlite3` command arguments.

**Comment by huacnlee** [comment]
Hi @rprtr258 I have fixed it again, and I tried it in local. 

The version v2.0.3 in releasing, you can try it.
