### ISSUE TITLE
S3 high memory using

### ISSUE THREAD

**Issue by alexkorotysh** [gobackup/gobackup#154]
Hi @huacnlee 
I am faced with high memory when uploading files to the S3 bucket. 
<img width="1495" alt="image" src="https://github.com/gobackup/gobackup/assets/15368568/8b9f9459-14ee-4aa6-80a3-18b00ce52e16">

Looks like we put object to RAM before sending to S3 bucket, maybe better to use [UploadWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#Uploader.UploadWithContext) instead of [Uploader](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#Uploader.Upload)

Ref: https://github.com/gobackup/gobackup/blob/main/storage/s3.go#L198

**Comment by alexkorotysh** [comment]
it didn't help me
<img width="1497" alt="image" src="https://github.com/gobackup/gobackup/assets/15368568/05dd611d-db4b-42c7-9c8e-2094ac42ee08">

**Comment by alexkorotysh** [comment]
<img width="679" alt="image" src="https://github.com/gobackup/gobackup/assets/15368568/39326af8-cc1e-47f0-9435-50e0c8df7403">
 during upload 25Gb dump to s3

**Comment by alexkorotysh** [comment]
Another example (gobackup v2.0.4)
<img width="1201" alt="image" src="https://github.com/gobackup/gobackup/assets/15368568/12f13eb7-09b8-46a8-be3d-51389364bae9">

**Comment by huacnlee** [comment]
@alexkorotysh That very helpful, thanks!

**Comment by huacnlee** [comment]
![20230512-110634](https://github.com/gobackup/gobackup/assets/5518/7dcc7fbd-9172-4d03-9592-92839d4ade0e)

I have written a 6 GB file in local and upload it by S3 storage, there looks like no memory issue.

**Comment by alexkorotysh** [comment]
I tried to run in docker images with base images alpine:latest and ubuntu:22.04 and it doesn't help.
@huacnlee could you please run your test inside docker container?

**Comment by alexkorotysh** [comment]
What do you think about pumping up version AWS SDK for go?
[Release v1.44.262 (2023-05-11)](https://github.com/aws/aws-sdk-go/releases)

**Comment by alexkorotysh** [comment]
well, I think the main point is that I run it in k8s with a docker image on amd64 arch, you probably run in another way with another arch

**Comment by alexkorotysh** [comment]
After upgrading k8s up to 1.24 from 1.23 
The container uses normal value of memory
<img width="1504" alt="image" src="https://github.com/gobackup/gobackup/assets/15368568/7c8ffed0-9c60-43e2-906c-83c848e89092">

I think we can close this issue. Thank for help!
