### ISSUE TITLE
可否指定配置文件位置?

### ISSUE THREAD

**Issue by pt-cc** [gobackup/gobackup#165]
<img width="833" alt="image" src="https://github.com/gobackup/gobackup/assets/19907364/0229c5a8-5f18-4faf-b9b5-54b4f50f4233">

我的配置文件放在 /etc/gobackup/gobackup.yml，使用 perform 说没有找到配置文件。使用 start 启动失败，使用run没有任何返回。
大佬，还是遇到类似的问题，有时间帮忙看下，多谢。

**Comment by huacnlee** [comment]
Same issue as #166 

And I have fixed this mistake.
