### ISSUE TITLE
[Config] Config file  not found

### ISSUE THREAD

**Issue by jcalado** [gobackup/gobackup#166]
Neither ~/.gobackup/gobackup.yml and /etc/gobackup/gobackup.yml work:

```
$ gobackup perform
[Config] Load config from default path.
[Config] Config file  not found.
```

running latest version, 
```
$ gobackup --version
gobackup version 2.3.1
```

**Comment by huacnlee** [comment]
New version in releasing, please wait v2.3.2 build.

https://github.com/gobackup/gobackup/actions/runs/5206885481
