### ISSUE TITLE
扩展功能

### ISSUE THREAD

**Issue by ziimee** [gobackup/gobackup#167]
可否支持 数据库名填多个数据库呢。免配置多个配置文件

**Comment by huacnlee** [comment]
数据库名填多个，是支持的，你直接配置多个数据库就可以了。

免配置多个配置文件 -- 没看懂

**Comment by ziimee** [comment]
意思只要填
databases:
      mysql:
        type: mysql
        host: localhost
        port: 3306
        database: my_database1 my_database2 my_database3
        username: root
        password: password

这样可以？

**Comment by huacnlee** [comment]
何必呢，你你配置两段，结果是一样的

ziimee ***@***.***>于2023年6月16日 周五下午9:24写道：

**Comment by pt-cc** [comment]
> 

一个实例中如果有10个db，如果备份其中的7个db，那就是需要写7段？

**Comment by bboysoulcn** [comment]
> 可否支持 数据库名填多个数据库呢。免配置多个配置文件

看了下代码，如果你要备份整个实例可以在 database 字段上填 `-A` 就好了
