### ISSUE TITLE
control characters are not allowed

### ISSUE THREAD

**Issue by pt-cc** [gobackup/gobackup#175]
./gobackup perform 启动的时候一直遇到这个问题，请问怎么解决？

<img width="1107" alt="image" src="https://github.com/gobackup/gobackup/assets/19907364/093046d1-2ccf-419b-af25-77aff0cc6fba">

**Comment by huacnlee** [comment]
YAML 的值，用引号

**Comment by pt-cc** [comment]
<img width="1233" alt="image" src="https://github.com/gobackup/gobackup/assets/19907364/65aa5ab6-4f00-494a-8ba2-bf5f14cf8c56">
加了引号依然是这个报错，而且我看文档都没有加引号，我这也没啥特殊字符

**Comment by huacnlee** [comment]
https://www.yamllint.com

检查一下

**Comment by pt-cc** [comment]
curl -sSL https://gobackup.github.io/install | sh    
上面的方式安装就是正常的。

使用 release 版本中的下载就不行。

**Comment by huacnlee** [comment]
应该不可能，CURL 和你直接走 release 下载是同一个东西

**Comment by pt-cc** [comment]
是不是跟 gobackup 执行文件放的位置有关系？ release 中下的放到 /usr/local/bin 下就可以。

遇到另外一个问题：
<img width="890" alt="image" src="https://github.com/gobackup/gobackup/assets/19907364/9842a1ea-f036-49a6-a42c-631a7b9bd360">
<img width="930" alt="image" src="https://github.com/gobackup/gobackup/assets/19907364/9da6cc0e-dc81-4a08-bba9-6e203a40568e">

**Comment by pt-cc** [comment]
centos7 ，选择的 [gobackup-linux-amd64.tar.gz](https://github.com/gobackup/gobackup/releases/download/v2.5.0/gobackup-linux-amd64.tar.gz)

**Comment by huacnlee** [comment]
```yml
models:
  your_model:
    storages:
      local:
        type: local
```

`storages` 下面的结构不对，得有一个名称。

**Comment by pt-cc** [comment]
感谢，release 下载的文件，需要移到类似 /bin 下面才行，不知道为什么 ./gobackup 这种就执行失败。目前可用了，多谢。

**Comment by huacnlee** [comment]
```
chmod +x ./gobackup
```

**Comment by bwlx** [comment]
报同样的错误，因为下载的 release 文件，解压后 gobackup 执行文件在家目录，后面把 gobackup 执行文件从家目录移除到别的地方后问题解决，因为执行也是在家目录执行的，感觉配置文件解析的时候去解析 gobackup 二进制文件了
