### ISSUE TITLE
使用minio作为存储，备份后无法获取备份的列表

### ISSUE THREAD

**Issue by pt-cc** [gobackup/gobackup#179]
![image](https://github.com/gobackup/gobackup/assets/19907364/aec37950-724c-4764-9e95-2d55a019482d)

storages 使用minio，备份后无法获取备份的列表。

**Comment by huacnlee** [comment]
<img width="940" alt="image" src="https://github.com/gobackup/gobackup/assets/5518/dcf1926a-8104-4598-8132-097ff808e509">

**Comment by huacnlee** [comment]
Just released v2.5.1 for fix this.
