### ISSUE TITLE
redis-cli SAVE failed /usr/bin/cp: target 'SAVE' is not a directory

### ISSUE THREAD

**Issue by Anbool** [gobackup/gobackup#180]
使用 copy 方式在定时任务中执行 redis 备份时，出现错误：redis-cli SAVE failed /usr/bin/cp: target 'SAVE' is not a directory
版本号：v2.5.0

**Comment by huacnlee** [comment]
```
invoke_save: false
```

设置一下，先用。我后续完善一下细节

**Comment by huacnlee** [comment]
Just released v2.5.1 for fix this.
