### ISSUE TITLE
docker 环境下配置文件变化，自动reload

### ISSUE THREAD

**Issue by pt-cc** [gobackup/gobackup#184]
遇到2个新的问题：

1. 在docker环境下，通过 vi 编辑 配置文件，是能够自动reload的，但是如果是通过 mv 或者 cp 导致文件变化后，不会自动reload，非docker环境是正常的；  
2. 通过web访问，找到某个model,点进目录后，可以正常显示，但是刷新后会显示404；  
3. 通过web进入某个model后，点击下载不成功。  

![image](https://github.com/gobackup/gobackup/assets/19907364/3d165001-bf68-4528-af94-0f5395091771)
![image](https://github.com/gobackup/gobackup/assets/19907364/62995a33-567d-4e10-9f9d-536cda462687)
![image](https://github.com/gobackup/gobackup/assets/19907364/db6a6086-fbea-478c-83a1-d5f5bfd0de2e)

**Comment by pt-cc** [comment]
补充一下，我的存储用的是 minio。感谢大神百忙之中还解决问题 😺

**Comment by huacnlee** [comment]
MinIO 我本地尝试了一下，可以下载的。

看你截图 URL 下载的 URL 也生成了，可能是其他原因，你查查

**Comment by pt-cc** [comment]
大概知道啥原因了，minio我配置的是 http://ip:9000,浏览器下载的时候提示使用http不安全，This download has been blocked，我想办法解决一下
