### ISSUE TITLE
Please add the ability to pass the config through the flag

### ISSUE THREAD

**Issue by injectionsuccesfully** [gobackup/gobackup#187]
I have simultaneous launches of different gobackups. And for different copies I need to use different configs
Example: 
gobackup perform -c "gobackup.yaml"

**Comment by injectionsuccesfully** [comment]
@huacnlee Thank you! perhaps the question is off topic, but can your application work with different configs at the same time? Recently I got a problem with duplicating the same notification, but with different configs.

**Comment by huacnlee** [comment]
You means you wants GoBackup merge multiple config files?

**Comment by injectionsuccesfully** [comment]
@huacnlee no, running the gobackup process at the same time with different configs will it work correctly?

**Comment by huacnlee** [comment]
You can run multiple gobackup prcessses at the same time.

for exmaple, you have `a.yml` and `b.yml` write difference config rules.


```
gobackup start -c a.yml
gobackup start -c b.yml
```

Now, you will have 2 gobackup processes.

**Comment by injectionsuccesfully** [comment]
@huacnlee Thank you very much for your help!!!
