### ISSUE TITLE
gobackup docker 升级后，升级前的文件就不能走keep的策略了

### ISSUE THREAD

**Issue by pt-cc** [gobackup/gobackup#195]
gobackup docker 升级后，升级前的文件就不能走keep的策略了，如果keep是3，升级后，备份文件会保持6个，升级前的不会被删除了，请问容器中有什么地方保留了备份的统计信息吗？

**Comment by huacnlee** [comment]
哦，这个是设计缺陷，之前在 ` ~/.gobackup/cycler` 文件夹里面存储了一个为每个 Model 存储了历史文件地址，Docker 无状态的情况下没这个东西。
