### ISSUE TITLE
gobackup tar的临时目录能不能自定义路径

### ISSUE THREAD

**Issue by jsntit** [gobackup/gobackup#197]
gobackup tar的临时目录设置为/tmp，但是我/tmp的空间不够，导致失败
能不能增加参数可以自定义路径

**Comment by huacnlee** [comment]
麻烦截图看一下错误

**Comment by jsntit** [comment]
![2023-11-09 093938](https://github.com/gobackup/gobackup/assets/743703/8b504da1-2475-422f-b157-ba1303bf274e)

**Comment by huacnlee** [comment]
你可以配置 `workdir` 来调整 GoBackup 使用的 `tmp` 的路径。

https://gobackup.github.io/configuration

**Comment by jsntit** [comment]
谢谢指导
