### ISSUE TITLE
Client gone, close stream

### ISSUE THREAD

**Issue by meesii** [gobackup/gobackup#198]
docker部署的方式运行了两天，今天早上没有自动备份。
查看docker日志提示Client gone, close stream
配置文件设置的是每日05:15

![image](https://github.com/gobackup/gobackup/assets/1815046/b05f9859-9956-4881-a981-308521d0caf8)

![image](https://github.com/gobackup/gobackup/assets/1815046/cee07942-174b-4b7e-b531-5f41b99dc2a2)

**Comment by huacnlee** [comment]
```
Client gone, close stream
```

这个是 Web UI 的提示，这个是 Web 界面 Log Stream 请求，不影响备份的。

你查一下是不是有其他问题。目前给到的信息暂时看不出问题。

**Comment by meesii** [comment]
发现问题了，是docker默认时区的问题。
