### ISSUE TITLE
建议备份目标存储考虑支持内置 http 支持

### ISSUE THREAD

**Issue by hick** [gobackup/gobackup#199]
包括 ftp/SFTP/SCP 等各种备份目标存储, 一般都涉及可能有别的用途的存储的账户和密码信息, 虽然也可以专门建账户降低账户信息扩散的风险, 也可以考虑 gobackup 自己的  HTTP 可以作为 Storage 可以接受 POST 过来的备份文件, 接受以后保存到本地文件. 

可以适当的内置简单的签名算法或者生成密码等方式. 

这样有多个机器的时候, 即可以形成分布式的多重备份, 不依赖 gobackup 以外的存储源, 自己就形成闭环了.

**Comment by huacnlee** [comment]
方向不同 GoBackup 是执行备份的，不是做存储的。存储有很多可选方案，就 SCP 和任何一个云存储都是非常简单且低成本的方案，GoBackup 没必要做此类事情。
