### ISSUE TITLE
Proposal for Collaboration on a Kubernetes Operator for gobackup

### ISSUE THREAD

**Issue by payamQorbanpour** [gobackup/gobackup#231]
Hello gobackup Team,

I am currently developing a Kubernetes operator that leverages gobackup to facilitate backing up databases and pushing them to various storage data sources. I propose that we collaborate on this initiative and consider creating a repository under the gobackup GitHub organization named gobackup-operator or anything you suggest. 

**Current Progress**
The operator is in its initial development phase, with the following milestones already achieved:

- Basic backup functionality for a variety of databases.
- Initial implementation of pushing backups to different storage solutions.
- Preliminary testing within a Kubernetes cluster environment.

I believe that with your support and collaboration, we can accelerate the development of the gobackup-operator, incorporating it seamlessly with the broader ecosystem of gobackup and providing valuable contributions to the community. I am open to discussing how we can align our efforts, share responsibilities, and officially kickstart this project under the gobackup organization.

Best regards,
Payam Qorbanpour

**Comment by pariviere** [comment]
Hello,

I'm very interested by the kind of operators and I'm looking for a way to integrate gobackup into my Kubernetes environments.

May I propose my help ? For testing, documentation and may be development ?

**Comment by payamQorbanpour** [comment]
> Hello,
> 
> I'm very interested by this kind of operators and I'm looking for a way to integrate gobackup into my Kubernetes environments.
> 
> May I propose my help ? For testing, documentation and may be development @payamQorbanpour

It would be an honor to collaborate with you on this project. However, I believe it's important to first await the response from the project's owners to ensure we understand their perspective. Should we not hear back from them, I plan to make my repository public and would be delighted to extend an invitation for you to collaborate with us at that stage.

**Comment by huacnlee** [comment]
https://github.com/gobackup/gobackup-operator

I have created a repo, and add you as the maintainer.
