### ISSUE TITLE
Problem installing on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by deoxyseia** [gobackup/gobackup#245]
OS: Ubuntu 24.04 LTS

Executed the installation line:

`curl -sSL https://gobackup.github.io/install | sh`

throws the following error

```

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Also I tried with super user but the error is the same.

**Comment by huacnlee** [comment]
Try this:

```bash
curl -v https://gobackup.github.io/install 
```

And send me the output please.

**Comment by deoxyseia** [comment]
curl -v https://gobackup.github.io/install

* Host gobackup.github.io:443 was resolved.
* IPv6: 2606:50c0:8000::153, 2606:50c0:8003::153, 2606:50c0:8002::153, 2606:50c0:8001::153
* IPv4: 185.199.110.153, 185.199.109.153, 185.199.111.153, 185.199.108.153
*   Trying 185.199.110.153:443...
* Connected to gobackup.github.io (185.199.110.153) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.io
*  start date: Mar 15 00:00:00 2024 GMT
*  expire date: Mar 14 23:59:59 2025 GMT
*  subjectAltName: host "gobackup.github.io" matched cert's "*.github.io"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://gobackup.github.io/install
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: gobackup.github.io]
* [HTTP/2] [1] [:path: /install]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET /install HTTP/2
> Host: gobackup.github.io
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/2 200
< server: GitHub.com
< content-type: application/octet-stream
< permissions-policy: interest-cohort=()
< last-modified: Tue, 05 Mar 2024 03:10:41 GMT
< access-control-allow-origin: *
< strict-transport-security: max-age=31556952
< etag: "65e68d31-59a"
< expires: Mon, 20 May 2024 14:35:21 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: 12D4:2EA192:59BDCF3:5BA6C24:664B5D51
< accept-ranges: bytes
< age: 0
< date: Mon, 20 May 2024 14:25:21 GMT
< via: 1.1 varnish
< x-served-by: cache-bfi-krnt7300020-BFI
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1716215122.717014,VS0,VE64
< vary: Accept-Encoding
< x-fastly-request-id: 67a70da48e1aaf5489cc00aafb8075a7c21b3162
< content-length: 1434
<
#!/usr/bin/env sh

set -u

type curl > /dev/null || { echo "curl: not found"; exit 1; }

set -e

get_latest_release() {
  local repo="$1"
	curl -sSL "https://api.github.com/repos/${repo}/releases/latest" | \
    awk 'BEGIN{FS=": |,|\""}; /tag_name/{print $5}'
}

repo="gobackup/gobackup"
version="$(get_latest_release "${repo}")"  # v1.2.0

# if args has version override it and not eq "latest"
if test $# -eq 1; then
  if test "$1" != "latest"; then
    version="$1"

    echo "Install ${version}"
  fi
fi

platform="$(uname | tr "[A-Z]" "[a-z]")"  # Linux => linux
arch="$(uname -m | sed 's/x86_64/amd64/')"  # x86_64 => amd64
package="gobackup-${platform}-${arch}.tar.gz"
package_url="https://github.com/${repo}/releases/download/${version}/${package}"
bin="gobackup"
dest_dir="/usr/local/bin"
bin_path="${dest_dir}/${bin}"
tmp_dir="$(mktemp -d)"

trap "rm -r ${tmp_dir}" EXIT

if test -e "${bin_path}"; then
  current_version="v$("${bin_path}" -v | awk '{print $NF}')"
  if test "${current_version}" = "${version}"; then
    echo "${bin} is already updated, no need to upgrade."
    exit 0
  else
    echo "There is a new version of ${bin}, starting to upgrade from ${current_version} to ${version}."
  fi
fi
cd "${tmp_dir}"
curl -sSL "${package_url}" | tar xzf -

if test $(id -u) -eq 0; then
  mv "${bin}" "${dest_dir}"
else
  sudo mv "${bin}" "${dest_dir}"
fi

mkdir -p ~/.gobackup

* Connection #0 to host gobackup.github.io left intact

**Comment by deoxyseia** [comment]
To bee more specific with this case, I'm using AWS EC2 instance, with Nitro System that is based on ARM architecture.

Checking the script I got the value of `package_url` variable:

`https://github.com/gobackup/gobackup/releases/download/v2.11.1/gobackup-linux-aarch64.tar.gz`

Trying the installation:
ubuntu@:~$ sh install
https://github.com/gobackup/gobackup/releases/download/v2.11.1/gobackup-linux-aarch64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by huacnlee** [comment]
Thank you report, I have fixed the installation script in https://github.com/gobackup/gobackup.github.io/commit/4292bde8592a19dfa59da2ee1fdcc19674a7aee6

Please try again.

**Comment by huacnlee** [comment]
Can you work now?

**Comment by deoxyseia** [comment]
There are a little error with a quote on `sed 's/aarch64/arm64/)"`

The error message:

```
ubuntu@:~$ curl -sSL https://gobackup.github.io/install | sh
sh: 59: Syntax error: Unterminated quoted string
```

**Comment by huacnlee** [comment]
Can you help me to check is this command work? I am now on Windows platform, can't test it.

```
uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/'
```

**Comment by huacnlee** [comment]
I have fixed it again, before commit I was had a typo.

https://github.com/gobackup/gobackup.github.io/commit/bb3f116df773c0b99443ff70f221501ed7e5f43a

**Comment by deoxyseia** [comment]
Tested and that works fine!!

```
ubuntu@:~$ curl -sSL https://gobackup.github.io/install | sh
gobackup v2.11.1 has been installed.
```

Thank you so much by the support.
